### ISSUE TITLE
implement que in between load cache and pubsubscribe

### ISSUE THREAD

**Issue by daverhub** [sp0n-7/pinballdb#5]
In pinball.js there is a case where an update might be missed during loadFromCache and pubSubcibe

try a que inbetween to start when loadcache in progress, then pop items off and load after loadFromCache complete.

trick, figure out if subscre should happen or should always que?

**Comment by victusfate** [comment]
was thinking more about this.

- loadfromcache
- update subscribe to
query to get updates since last (sync & subscribe)

ps this is a public repo (no private deps)

**Comment by victusfate** [comment]
heads up I quieted the warnings for now and linked to this issue to avoid the L20 errors (crazy log spam)

now it'll just silently eat up cpu during startup but it appears to recover aok
